workflows:
  fastlane-android-build:
    name: Fastlane Android Build
    max_build_duration: 60
    environment:
      node: 18.16.0
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd android 
          bundle install
      - name: Run Fastlane build
        script: |
          cd android
          fastlane build
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - 1234swayamsamyak@gmail.com
        notify:
          on_success: true
          on_failure: true
